services:
  shrubbery:
    image: ghcr.io/flipstone/haskell-tools:debian-stable-ghc-9.4.6-2023-08-29-52330cd
    volumes:
      - .:${PROJECT_DIR}
      - flipstone_stack_root:/stack-root
    environment:
      STACK_ROOT: /stack-root
      IN_DEV_CONTAINER: 'true'
      # Pass through the CI variable from GitHub (or set it to `true` locally
      # for debugging CI builds)
      CI:
    working_dir: ${PROJECT_DIR}
    tty: true

volumes:
  flipstone_stack_root:
    external: true
