[language-server.haskell-language-server]
command = "haskell-language-server-wrapper"
args = ["--lsp"]

[language-server.haskell-language-server.config]
haskell.formattingProvider = "fourmolu"
# Uncomment this to stop the HLS crash from happening
# haskell.plugin.hlint.globalOn = false
